disabled_rules: # rule identifiers to exclude from running
  - comment_spacing
  - large_tuple

cyclomatic_complexity:
  warning: 25 # two nested ifs are acceptable
  error: 50   # six nested ifs shows error

opt_in_rules: # some rules are only opt-in
  # - empty_count
  # Find all available rules by running: swiftlint rules

#included: # paths to include during linting. --path is ignored if present.
#  - Source

excluded: # paths to ignore during linting. Takes precedence over included.
  - Carthage
  - Pods
  - GenderTests
  - AppFolder\ App/Class/*
  - CryptoSwiftFramework
  # - AppFolder\ App/ViewController/*

analyzer_rules: # Rules run by swiftlint analyze (experimental)
  - explicit_self

force_cast: warning
force_try:
  severity: warning

line_length:
  warning: 250
  error: 500
  ignores_comments: true
  ignores_urls: true

type_body_length:
  - 300 # warning
  - 600 # error

file_length:
  warning: 500
  error: 2500

function_body_length:
  - 200 # warning
  - 300 # error

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey

custom_rules:
  no_unused_print:
    name: "No Unused Print Statements"
    description: "Avoid using `print` statements in production code."
    regex: '\bprint\s*\('
    severity: warning

reporter: "xcode"
